import React from 'react'
import CommunitySearch from './CommunitySearch'

const ImageGrid = () => {
  return (
    <div className='flex flex-col items-start mt-0'>
        <h1 className='font-extrabold text-[#222328] text-[2rem]'>The Community Showcase</h1>
        <p className='text-[#666e75] text-[0.9rem] max-w-[700px]  mb-6'>Browse through a collection of imagination and visually stunning images generated by Doppo.</p>
        <CommunitySearch/>
        <div className="grid mt-8"></div>
    </div>
  )
}

export default ImageGrid