import React, { useState } from 'react';
import Cards from './Cards';

const ImageGrid = ({ data }) => {
  const [search, setSearch] = useState('');

  const makeArray = () => {
    let arr = [];
    data.forEach((element) => {
      element.images.forEach((item) => {
        arr.push({
          userName: element.userName,
          prompt: element.prompt,
          url: item,
        });
      });
    });
    return arr.reverse();
  };


  return (
    <div className='flex flex-col items-start mt-0'>
      <h1 className='font-extrabold text-[#222328] sm:text-[2rem] text-[1.75rem]'>
        The Community Library
      </h1>
      <p className='text-[#666e75] text-[0.9rem] max-w-[700px]  mb-6'>
        Browse through a collection of imagination and visually stunning images
        generated by ImageGen.
      </p>
      {/* <CommunitySearch /> */}
      <div className='w-full flex flex-col items-start gap-5'>
        <span className='flex items-center justify-center gap-2'>
          <p className='text-[#777] text-sm font-bold'>
            Search in the library.
          </p>
        </span>
        <div className='h-fit overflow-hidden pl-4 w-full rounded-md shadow-md bg-clip-border flex justify-between items-center'>
          <input
            required
            value={search && `${search}`}
            onChange={(e) => setSearch(e.target.value)}
            placeholder='Eg: Gun'
            type='text'
            className='py-3 px-4 text-black bg-white w-full border-none outline-none'
          />
          {/* <button
            onClick={(e) => handleSearchClick(e)}
            className={`${
              search ? 'bg-black text-white' : 'text-[#777] hover:text-black'
            } py-3 border-l border-l-[#e6ebf4] px-3`}
          >
            Search
          </button> */}
        </div>
      </div>
      <div className='py-8 w-full'>
        <Cards data={makeArray()} search={search} />
      </div>
    </div>
  );
};

export default ImageGrid;
